INSERT INTO philippine_regions (psgc_code, name, region_code, created_at) VALUES ('010000000', 'REGION I (ILOCOS REGION)', '01', DEFAULT);
INSERT INTO philippine_regions (psgc_code, name, region_code, created_at) VALUES ('020000000', 'REGION II (CAGAYAN VALLEY)', '02', DEFAULT);
INSERT INTO philippine_regions (psgc_code, name, region_code, created_at) VALUES ('030000000', 'REGION III (CENTRAL LUZON)', '03', DEFAULT);
INSERT INTO philippine_regions (psgc_code, name, region_code, created_at) VALUES ('040000000', 'REGION IV-A (CALABARZON)', '04', DEFAULT);
INSERT INTO philippine_regions (psgc_code, name, region_code, created_at) VALUES ('170000000', 'REGION IV-B (MIMAROPA)', '17', DEFAULT);
INSERT INTO philippine_regions (psgc_code, name, region_code, created_at) VALUES ('050000000', 'REGION V (BICOL REGION)', '05', DEFAULT);
INSERT INTO philippine_regions (psgc_code, name, region_code, created_at) VALUES ('060000000', 'REGION VI (WESTERN VISAYAS)', '06', DEFAULT);
INSERT INTO philippine_regions (psgc_code, name, region_code, created_at) VALUES ('070000000', 'REGION VII (CENTRAL VISAYAS)', '07', DEFAULT);
INSERT INTO philippine_regions (psgc_code, name, region_code, created_at) VALUES ('080000000', 'REGION VIII (EASTERN VISAYAS)', '08', DEFAULT);
INSERT INTO philippine_regions (psgc_code, name, region_code, created_at) VALUES ('090000000', 'REGION IX (ZAMBOANGA PENINSULA)', '09', DEFAULT);
INSERT INTO philippine_regions (psgc_code, name, region_code, created_at) VALUES ('100000000', 'REGION X (NORTHERN MINDANAO)', '10', DEFAULT);
INSERT INTO philippine_regions (psgc_code, name, region_code, created_at) VALUES ('110000000', 'REGION XI (DAVAO REGION)', '11', DEFAULT);
INSERT INTO philippine_regions (psgc_code, name, region_code, created_at) VALUES ('120000000', 'REGION XII (SOCCSKSARGEN)', '12', DEFAULT);
INSERT INTO philippine_regions (psgc_code, name, region_code, created_at) VALUES ('130000000', 'NATIONAL CAPITAL REGION (NCR)', '13', DEFAULT);
INSERT INTO philippine_regions (psgc_code, name, region_code, created_at) VALUES ('140000000', 'CORDILLERA ADMINISTRATIVE REGION (CAR)', '14', DEFAULT);
INSERT INTO philippine_regions (psgc_code, name, region_code, created_at) VALUES ('150000000', 'BANGSAMORO AUTONOMOUS REGION IN MUSLIM MINDANAO (BARMM)', '15', DEFAULT);
INSERT INTO philippine_regions (psgc_code, name, region_code, created_at) VALUES ('160000000', 'REGION XIII (Caraga)', '16', DEFAULT);
