import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import { Head, usePage, router } from '@inertiajs/react';
import TableComponent from '@/Components/AdminLayout/table';
import { useState } from 'react';
import {
  TableBody,
  TableCell,
  TableRow,
} from "@/components/ui/table";
import { toast } from 'sonner';
import { Trash2, Eye, Download, FileText, Filter, FileDown } from 'lucide-react';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Button } from '@/Components/ui/button';
import {
  Popover,
  PopoverContent,
  PopoverTrigger,
} from "@/components/ui/popover";
import * as XLSX from "xlsx";

import CreateReport from './create';
import ViewReport from './show';
import DeleteReport from './delete';

export default function ReportManagement() {
    const columns = [
        { header: 'Report Title', width: '25%' },
        { header: 'Type', width: '15%' },
        { header: 'Period', width: '12%' },
        { header: 'Date Range', width: '18%' },
        { header: 'Status', width: '10%' },
        { header: 'Generated', width: '12%' },
        { header: 'Action', width: '10%' },
    ];

    const [showCreateModal, setShowCreateModal] = useState(false);
    const [showViewModal, setShowViewModal] = useState(false);
    const [viewReport, setViewReport] = useState(null);
    const [showDeleteModal, setShowDeleteModal] = useState(false);
    const [deleteReport, setDeleteReport] = useState(null);
    const [showFilterPopover, setShowFilterPopover] = useState(false);

    const pagination = usePage().props.reports;
    const reportData = usePage().props.reports.data;

    const [search, setSearch] = useState(usePage().props.search || '');
    const [typeFilter, setTypeFilter] = useState(usePage().props.typeFilter || '');
    const [statusFilter, setStatusFilter] = useState(usePage().props.statusFilter || '');
    const [periodFilter, setPeriodFilter] = useState(usePage().props.periodFilter || '');

    const handleSearch = (e) => {
        setSearch(e.target.value);
        router.get(
            route('admin.reporting-management.index'), 
            { 
                search: e.target.value,
                type: typeFilter,
                status: statusFilter,
                period: periodFilter
            }, 
            { preserveState: true, replace: true }
        );
    };

    const handleFilterChange = (type, value) => {
        if (type === 'type') {
            setTypeFilter(value);
        } else if (type === 'status') {
            setStatusFilter(value);
        } else if (type === 'period') {
            setPeriodFilter(value);
        }

        router.get(
            route('admin.reporting-management.index'),
            {
                search,
                type: type === 'type' ? value : typeFilter,
                status: type === 'status' ? value : statusFilter,
                period: type === 'period' ? value : periodFilter,
            },
            { preserveState: true, replace: true }
        );
    };

    const handleClearFilters = () => {
        setTypeFilter('');
        setStatusFilter('');
        setPeriodFilter('');
        
        router.get(
            route('admin.reporting-management.index'),
            {
                search,
                type: '',
                status: '',
                period: '',
            },
            { preserveState: true, replace: true }
        );
    };

    const handlePageChange = ({ search, page }) => {
        router.get(
            route('admin.reporting-management.index'), 
            { 
                search, 
                page,
                type: typeFilter,
                status: statusFilter,
                period: periodFilter
            }, 
            { preserveState: true, replace: true }
        );
    };

    const handleExportAll = () => {
        try {
            const rows = reportData.map((report) => {
                const summaryStats = report.summary_stats || {};
                
                return {
                    "Report Title": report.report_title || 'N/A',
                    "Report Type": getReportTypeName(report.report_type),
                    "Period": report.report_period ? report.report_period.charAt(0).toUpperCase() + report.report_period.slice(1) : 'N/A',
                    "Start Date": report.start_date ? formatDate(report.start_date) : 'N/A',
                    "End Date": report.end_date ? formatDate(report.end_date) : 'N/A',
                    "Status": report.status ? report.status.charAt(0).toUpperCase() + report.status.slice(1) : 'N/A',
                    "Generated At": report.generated_at ? formatDate(report.generated_at) : 'Not Generated',
                    "Generated By": report.generated_by?.name || 'N/A',
                    "Description": report.description || 'N/A',
                    ...summaryStats
                };
            });

            if (rows.length === 0) {
                toast.error("No reports to export");
                return;
            }

            const worksheet = XLSX.utils.json_to_sheet(rows);
            const workbook = XLSX.utils.book_new();
            XLSX.utils.book_append_sheet(workbook, worksheet, "Reports");

            // Auto-size columns
            const maxWidth = 50;
            const colWidths = Object.keys(rows[0]).map(key => {
                const maxLen = Math.max(
                    key.length,
                    ...rows.map(row => String(row[key] || '').length)
                );
                return { wch: Math.min(maxLen + 2, maxWidth) };
            });
            worksheet['!cols'] = colWidths;

            const dateStamp = new Date().toISOString().slice(0, 10);
            const fileName = `reports-summary-${dateStamp}.xlsx`;
            
            XLSX.writeFile(workbook, fileName);

            toast.success("Reports exported successfully!");
        } catch (error) {
            console.error(error);
            toast.error("Failed to export reports");
        }
    };

    const handleExportSingle = (report) => {
        try {
            if (report.status !== 'completed') {
                toast.error("Can only export completed reports");
                return;
            }

            const reportData = report.report_data || {};
            const summaryStats = report.summary_stats || {};

            // Create main report info
            const mainInfo = [{
                "Report Title": report.report_title,
                "Report Type": getReportTypeName(report.report_type),
                "Period": report.report_period,
                "Start Date": formatDate(report.start_date),
                "End Date": formatDate(report.end_date),
                "Generated At": formatDate(report.generated_at),
                "Generated By": report.generated_by?.name || 'N/A',
                "Description": report.description || 'N/A',
            }];

            const workbook = XLSX.utils.book_new();

            // Add Report Info sheet
            const infoSheet = XLSX.utils.json_to_sheet(mainInfo);
            XLSX.utils.book_append_sheet(workbook, infoSheet, "Report Info");

            // Add Summary Stats sheet if available
            if (Object.keys(summaryStats).length > 0) {
                const statsData = Object.entries(summaryStats).map(([key, value]) => ({
                    "Metric": key.replace(/_/g, ' ').replace(/\b\w/g, l => l.toUpperCase()),
                    "Value": value
                }));
                const statsSheet = XLSX.utils.json_to_sheet(statsData);
                XLSX.utils.book_append_sheet(workbook, statsSheet, "Summary Stats");
            }

            // Add detailed data based on report type
            if (Object.keys(reportData).length > 0) {
                addReportDataSheets(workbook, reportData, report.report_type);
            }

            // Auto-size all columns
            workbook.SheetNames.forEach(sheetName => {
                const worksheet = workbook.Sheets[sheetName];
                const range = XLSX.utils.decode_range(worksheet['!ref']);
                const colWidths = [];
                
                for (let C = range.s.c; C <= range.e.c; ++C) {
                    let maxWidth = 10;
                    for (let R = range.s.r; R <= range.e.r; ++R) {
                        const cellAddress = XLSX.utils.encode_cell({ r: R, c: C });
                        const cell = worksheet[cellAddress];
                        if (cell && cell.v) {
                            const cellLength = String(cell.v).length;
                            maxWidth = Math.max(maxWidth, cellLength);
                        }
                    }
                    colWidths.push({ wch: Math.min(maxWidth + 2, 50) });
                }
                worksheet['!cols'] = colWidths;
            });

            const dateStamp = new Date().toISOString().slice(0, 10);
            const fileName = `${report.report_title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}-${dateStamp}.xlsx`;
            
            XLSX.writeFile(workbook, fileName);

            toast.success("Report exported successfully!");
        } catch (error) {
            console.error(error);
            toast.error("Failed to export report");
        }
    };

    const addReportDataSheets = (workbook, reportData, reportType) => {
        switch(reportType) {
            case 'collection_summary':
                if (reportData.by_status) {
                    const statusData = reportData.by_status.map(item => ({
                        "Status": item.status,
                        "Count": item.count
                    }));
                    const statusSheet = XLSX.utils.json_to_sheet(statusData);
                    XLSX.utils.book_append_sheet(workbook, statusSheet, "By Status");
                }
                if (reportData.by_waste_type) {
                    const wasteData = reportData.by_waste_type.map(item => ({
                        "Waste Type": item.waste_type,
                        "Count": item.count
                    }));
                    const wasteSheet = XLSX.utils.json_to_sheet(wasteData);
                    XLSX.utils.book_append_sheet(workbook, wasteSheet, "By Waste Type");
                }
                if (reportData.daily_breakdown) {
                    const dailyData = reportData.daily_breakdown.map(item => ({
                        "Date": item.date,
                        "Count": item.count
                    }));
                    const dailySheet = XLSX.utils.json_to_sheet(dailyData);
                    XLSX.utils.book_append_sheet(workbook, dailySheet, "Daily Breakdown");
                }
                break;

            case 'collector_performance':
                if (reportData.collectors) {
                    const collectorSheet = XLSX.utils.json_to_sheet(reportData.collectors);
                    XLSX.utils.book_append_sheet(workbook, collectorSheet, "Collectors");
                }
                if (reportData.top_performers) {
                    const topSheet = XLSX.utils.json_to_sheet(reportData.top_performers);
                    XLSX.utils.book_append_sheet(workbook, topSheet, "Top Performers");
                }
                break;

            case 'resident_activity':
                if (reportData.top_requesters) {
                    const requestersSheet = XLSX.utils.json_to_sheet(reportData.top_requesters);
                    XLSX.utils.book_append_sheet(workbook, requestersSheet, "Top Requesters");
                }
                if (reportData.by_barangay) {
                    const barangayData = Object.entries(reportData.by_barangay).map(([key, value]) => ({
                        "Barangay": key,
                        "Count": value
                    }));
                    const barangaySheet = XLSX.utils.json_to_sheet(barangayData);
                    XLSX.utils.book_append_sheet(workbook, barangaySheet, "By Barangay");
                }
                break;

            case 'barangay_statistics':
                if (reportData.barangay_data) {
                    const barangaySheet = XLSX.utils.json_to_sheet(reportData.barangay_data);
                    XLSX.utils.book_append_sheet(workbook, barangaySheet, "Barangay Data");
                }
                break;

            case 'route_efficiency':
                if (reportData.route_statistics) {
                    const routeSheet = XLSX.utils.json_to_sheet(reportData.route_statistics);
                    XLSX.utils.book_append_sheet(workbook, routeSheet, "Route Statistics");
                }
                if (reportData.most_efficient_routes) {
                    const efficientSheet = XLSX.utils.json_to_sheet(reportData.most_efficient_routes);
                    XLSX.utils.book_append_sheet(workbook, efficientSheet, "Most Efficient");
                }
                break;

            default:
                // For other types, try to add any array data
                Object.entries(reportData).forEach(([key, value]) => {
                    if (Array.isArray(value) && value.length > 0) {
                        const sheet = XLSX.utils.json_to_sheet(value);
                        const sheetName = key.replace(/_/g, ' ').replace(/\b\w/g, l => l.toUpperCase()).substring(0, 31);
                        XLSX.utils.book_append_sheet(workbook, sheet, sheetName);
                    }
                });
        }
    };

    const getStatusBadge = (status) => {
        const badges = {
            completed: 'bg-green-100 text-green-800',
            pending: 'bg-yellow-100 text-yellow-800',
            generating: 'bg-blue-100 text-blue-800',
            failed: 'bg-red-100 text-red-800'
        };
        return badges[status] || 'bg-gray-100 text-gray-800';
    };

    const getReportTypeName = (type) => {
        const types = {
            collection_summary: 'Collection Summary',
            collector_performance: 'Collector Performance',
            resident_activity: 'Resident Activity',
            waste_bin_status: 'Waste Bin Status',
            route_efficiency: 'Route Efficiency',
            schedule_compliance: 'Schedule Compliance',
            barangay_statistics: 'Barangay Statistics',
            waste_type_analysis: 'Waste Type Analysis',
            monthly_overview: 'Monthly Overview',
            custom: 'Custom Report'
        };
        return types[type] || type;
    };

    const formatDate = (dateString) => {
        if (!dateString) return '---';
        return new Date(dateString).toLocaleDateString('en-US', {
            year: 'numeric',
            month: 'short',
            day: 'numeric'
        });
    };

    const hasActiveFilters = typeFilter || statusFilter || periodFilter;

    const breadcrumbs = [
        {
            name: "Home",
            href: route('dashboard'),
        },
        {
            name: "Reports",
        },
    ];

    const reportTypes = [
        { value: 'collection_summary', label: 'Collection Summary' },
        { value: 'collector_performance', label: 'Collector Performance' },
        { value: 'resident_activity', label: 'Resident Activity' },
        { value: 'waste_bin_status', label: 'Waste Bin Status' },
        { value: 'route_efficiency', label: 'Route Efficiency' },
        { value: 'schedule_compliance', label: 'Schedule Compliance' },
        { value: 'barangay_statistics', label: 'Barangay Statistics' },
        { value: 'waste_type_analysis', label: 'Waste Type Analysis' },
        { value: 'monthly_overview', label: 'Monthly Overview' },
    ];

    const reportStatuses = [
        { value: 'completed', label: 'Completed' },
        { value: 'pending', label: 'Pending' },
        { value: 'generating', label: 'Generating' },
        { value: 'failed', label: 'Failed' },
    ];

    const reportPeriods = [
        { value: 'daily', label: 'Daily' },
        { value: 'weekly', label: 'Weekly' },
        { value: 'monthly', label: 'Monthly' },
        { value: 'quarterly', label: 'Quarterly' },
        { value: 'yearly', label: 'Yearly' },
        { value: 'custom', label: 'Custom' },
    ];

    return (
        <>
        {showCreateModal && (
            <CreateReport setShowCreateModal={setShowCreateModal} />
        )}

        {showViewModal && (
            <ViewReport 
                setShowViewModal={setShowViewModal} 
                report={viewReport}
                onExport={handleExportSingle}
            />
        )}
        
        {showDeleteModal && (
            <DeleteReport 
                setShowDeleteModal={setShowDeleteModal} 
                report={deleteReport}
            />
        )}

        <AuthenticatedLayout breadcrumbs={breadcrumbs}>
            <Head title="Report Management" />

            <div>
                <div className="w-full sm:px-6 lg:px-8">
                    {/* Custom header with search, filters, and add button */}
                    <div className="p-2 bg-white rounded-md shadow mb-2">
                        <div className="py-2 flex flex-col sm:flex-row sm:items-center gap-2">
                            {/* Search Input */}
                            <div className="w-full sm:flex-1">
                                <input
                                    type="text"
                                    placeholder="Search reports..."
                                    value={search}
                                    onChange={handleSearch}
                                    className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-gray-800 focus:border-gray-800"
                                />
                            </div>

                            {/* Filter Button with Popover */}
                            <div className="w-full sm:w-auto">
                                <Popover open={showFilterPopover} onOpenChange={setShowFilterPopover}>
                                    <PopoverTrigger asChild>
                                        <Button 
                                            variant="outline"
                                            className="w-full sm:w-auto relative"
                                        >
                                            <Filter size={16} className="mr-2" />
                                            Filters
                                            {hasActiveFilters && (
                                                <span className="absolute -top-1 -right-1 h-4 w-4 bg-red-500 rounded-full text-xs text-white flex items-center justify-center">
                                                    {[typeFilter, statusFilter, periodFilter].filter(Boolean).length}
                                                </span>
                                            )}
                                        </Button>
                                    </PopoverTrigger>
                                    <PopoverContent className="w-80" align="end">
                                        <div className="space-y-4">
                                            <div className="flex items-center justify-between">
                                                <h4 className="font-semibold text-sm">Filters</h4>
                                                {hasActiveFilters && (
                                                    <Button
                                                        variant="ghost"
                                                        size="sm"
                                                        onClick={handleClearFilters}
                                                        className="h-auto p-1 text-xs"
                                                    >
                                                        Clear All
                                                    </Button>
                                                )}
                                            </div>

                                            {/* Type Filter */}
                                            <div>
                                                <label className="text-xs font-medium text-zinc-700 mb-1 block">
                                                    Report Type
                                                </label>
                                                <Select 
                                                    value={typeFilter} 
                                                    onValueChange={(value) => handleFilterChange('type', value)}
                                                >
                                                    <SelectTrigger className="w-full">
                                                        <SelectValue placeholder="All Types" />
                                                    </SelectTrigger>
                                                    <SelectContent>
                                                        <SelectItem value="all">All Types</SelectItem>
                                                        {reportTypes.map(type => (
                                                            <SelectItem key={type.value} value={type.value}>
                                                                {type.label}
                                                            </SelectItem>
                                                        ))}
                                                    </SelectContent>
                                                </Select>
                                            </div>

                                            {/* Status Filter */}
                                            <div>
                                                <label className="text-xs font-medium text-zinc-700 mb-1 block">
                                                    Status
                                                </label>
                                                <Select 
                                                    value={statusFilter} 
                                                    onValueChange={(value) => handleFilterChange('status', value)}
                                                >
                                                    <SelectTrigger className="w-full">
                                                        <SelectValue placeholder="All Status" />
                                                    </SelectTrigger>
                                                    <SelectContent>
                                                        <SelectItem value="all">All Status</SelectItem>
                                                        {reportStatuses.map(status => (
                                                            <SelectItem key={status.value} value={status.value}>
                                                                {status.label}
                                                            </SelectItem>
                                                        ))}
                                                    </SelectContent>
                                                </Select>
                                            </div>

                                            {/* Period Filter */}
                                            <div>
                                                <label className="text-xs font-medium text-zinc-700 mb-1 block">
                                                    Period
                                                </label>
                                                <Select 
                                                    value={periodFilter} 
                                                    onValueChange={(value) => handleFilterChange('period', value)}
                                                >
                                                    <SelectTrigger className="w-full">
                                                        <SelectValue placeholder="All Periods" />
                                                    </SelectTrigger>
                                                    <SelectContent>
                                                        <SelectItem value="all">All Periods</SelectItem>
                                                        {reportPeriods.map(period => (
                                                            <SelectItem key={period.value} value={period.value}>
                                                                {period.label}
                                                            </SelectItem>
                                                        ))}
                                                    </SelectContent>
                                                </Select>
                                            </div>
                                        </div>
                                    </PopoverContent>
                                </Popover>
                            </div>

                            {/* Export All Button */}
                            <div className="w-full sm:w-auto">
                                <Button
                                    variant="outline"
                                    onClick={handleExportAll}
                                    className="w-full sm:w-auto gap-2"
                                    disabled={reportData.length === 0}
                                >
                                    <FileDown size={16} />
                                    Export All
                                </Button>
                            </div>

                            {/* Create Report Button */}
                            <div className="w-full sm:w-auto">
                                <Button 
                                    className="w-full sm:w-auto bg-green-600 hover:bg-green-700 text-white" 
                                    onClick={() => setShowCreateModal(true)}
                                >
                                    <FileText size={18} className="mr-2" />
                                    Create Report
                                </Button>
                            </div>
                        </div>
                    </div>

                    {/* Table */}
                    <TableComponent
                        columns={columns}
                        data={reportData}
                        pagination={pagination}
                        search={search}
                        onPageChange={handlePageChange}
                        showSearch={false}
                        showAddButton={false}
                    >
                        {reportData.map(report => (
                            <TableRow key={report.id}>
                                <TableCell className='text-left px-2 py-2 sm:px-4 md:px-6 text-xs sm:text-sm'>
                                    {report.report_title}
                                </TableCell>
                                <TableCell className='text-left px-2 py-2 sm:px-4 md:px-6 text-xs sm:text-sm'>
                                    {getReportTypeName(report.report_type)}
                                </TableCell>
                                <TableCell className='text-left px-2 py-2 sm:px-4 md:px-6 text-xs sm:text-sm'>
                                    <span className="capitalize">{report.report_period}</span>
                                </TableCell>
                                <TableCell className='text-left px-2 py-2 sm:px-4 md:px-6 text-xs sm:text-sm'>
                                    {formatDate(report.start_date)} - {formatDate(report.end_date)}
                                </TableCell>
                                <TableCell className='text-left px-2 py-2 sm:px-4 md:px-6 text-xs sm:text-sm'>
                                    <span className={`px-2 py-1 rounded-full text-xs capitalize ${getStatusBadge(report.status)}`}>
                                        {report.status}
                                    </span>
                                </TableCell>
                                <TableCell className='text-left px-2 py-2 sm:px-4 md:px-6 text-xs sm:text-sm'>
                                    {report.generated_at ? formatDate(report.generated_at) : '---'}
                                </TableCell>
                                <TableCell className='text-left px-2 py-2 sm:px-4 md:px-6 text-xs sm:text-sm'>
                                    <div className="flex gap-2">
                                        <button
                                            onClick={() => {
                                                setViewReport(report);
                                                setShowViewModal(true);
                                            }}
                                            className="p-2 rounded hover:bg-blue-100 text-blue-600 hover:text-blue-700 transition"
                                            title="View Report"
                                            aria-label="View"
                                            type="button"
                                        >
                                            <Eye size={18} />
                                        </button>
                                        {report.status === 'completed' && (
                                            <button
                                                onClick={() => handleExportSingle(report)}
                                                className="p-2 rounded hover:bg-green-100 text-green-600 hover:text-green-700 transition"
                                                title="Download Report"
                                                aria-label="Download"
                                                type="button"
                                            >
                                                <Download size={18} />
                                            </button>
                                        )}
                                        <button
                                            onClick={() => {
                                                setDeleteReport(report);
                                                setShowDeleteModal(true);
                                            }}
                                            className="p-2 rounded hover:bg-red-100 text-red-600 hover:text-red-700 transition"
                                            title="Delete"
                                            aria-label="Delete"
                                            type="button"
                                        >
                                            <Trash2 size={18} />
                                        </button>
                                    </div>
                                </TableCell>
                            </TableRow>
                        ))}
                    </TableComponent>
                </div>
            </div>
        </AuthenticatedLayout>
        </>
    );
}